name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2.5.0
      
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1.2.0
      
    - name: Restore NuGet packages
      run:  nuget restore ESTOSMetadirectory2InnovaphoneContacts.sln
      
    - name: Build
      run:  msbuild ESTOSMetadirectory2InnovaphoneContacts.sln /p:Configuration=Release
      